[package]
name = "over-yonder-desktop"
version = "0.0.0"
description = "Over Yonder desktop app"
authors = ["Over Yonder"]
edition = "2021"

[lib]
name = "over_yonder_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
